# FROM maven:3.8.1-openjdk-17-slim AS MAVEN_BUILD
FROM maven:3.8.1-openjdk-17 AS MAVEN_BUILD
EXPOSE 8082
WORKDIR /app

ARG JAR_FILE=target/first-0.0.1-SNAPSHOT.jar

COPY pom.xml .
COPY src ./src
COPY target ./target

RUN mvn package -Dmaven.test.skip=true

FROM adoptopenjdk/openjdk16:alpine-jre

WORKDIR /opt/app

COPY --from=MAVEN_BUILD ./${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]