version: '3.4'

services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    restart: unless-stopped
  # APP*****************************************
  spring-boot-docker:
    # image: first
    network_mode: bridge
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8082
    ports:
      - 8082:8082
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    # restart: always
volumes:
  postgres-data: